import { GraphNode, TextAnchor, Conversation } from "@/types/graph";

export const DEMO_CONVERSATION_SAD_GAANA: {
  conversation: Conversation;
  nodes: GraphNode[];
  anchors: TextAnchor[];
} = {
  conversation: {
    id: "conv-sad-gaana-1",
    title: "Sad Gaana — Hindi Lyrics & Breakdown",
    rootNodeId: "node-user-1",
    currentNodeId: "node-ai-2",
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now(),
  },
  nodes: [
    {
      id: "node-user-1",
      conversationId: "conv-sad-gaana-1",
      type: "user",
      content: "Explain the song 'Sad Gaana' to me and help me understand the Hindi.",
      parentId: null,
      isMainPath: true,
      mainPathIndex: 0,
      position: { x: 50, y: 50 },
      collapsed: false,
      createdAt: Date.now() - 3500000,
    },
    {
      id: "node-ai-1",
      conversationId: "conv-sad-gaana-1",
      type: "assistant",
      content:
        "**'Sad Gaana'** is an introspective hip-hop track exploring mental exhaustion, raw familial expectations, and vulnerability amidst creative hustle.\n\nHere are the pivotal lines that set the emotional landscape:\n\n> *\"मेरी माँ को भरोसा मेरे पे, कितना फ़क्र देख\"*\n> *(My mother believes in me, look how much pride she has)*\n\n> *\"थक चुका हूँ मैं, पर रुक नहीं सकता\"*\n> *(I am utterly exhausted, yet I cannot afford to stop)*\n\n> *\"गाँड फाड़ दूँगा, एक छोटी सी कहावत सी\"*\n> *(I'll tear it up, almost like a casual colloquial proverb)*\n\nThe artist juxtaposes poignant tender love with fierce street-level determination. Select any Hindi word or concept above to dissect its slang, cultural origin, and figurative weight.",
      parentId: "node-user-1",
      isMainPath: true,
      mainPathIndex: 1,
      position: { x: 50, y: 350 },
      collapsed: false,
      createdAt: Date.now() - 3400000,
      metadata: {
        contextSentence: "Key lyric breakdown with raw emotional undertones",
      },
    },
    {
      id: "node-exp-fakr",
      conversationId: "conv-sad-gaana-1",
      type: "exploration",
      promptQuestion: "What does फ़क्र mean?",
      actionType: "explain",
      content:
        "### फ़क्र (Fakr / Fakhr)\n\n**Literal Meaning:** Pride, honor, profound sense of dignity (Urdu/Hindi origin: *فخر*).\n\n**Cultural Nuance:**\nIn South Asian families, maternal pride is considered sacred. When he mentions *\"मेरी माँ को भरोसा मेरे पे, कितना फ़क्र देख\"*, the word **फ़क्र** carries a double-edged sword:\n1. It is his ultimate driving fuel (he cannot let her down).\n2. It becomes an intense psychological pressure where failure is not an option.",
      parentId: "node-ai-1",
      isMainPath: false,
      position: { x: 550, y: 220 },
      collapsed: false,
      createdAt: Date.now() - 3200000,
      anchor: {
        sourceNodeId: "node-ai-1",
        text: "फ़क्र",
        start: 228,
        end: 232,
        actionType: "explain",
      },
      metadata: {
        contextSentence: "मेरी माँ को भरोसा मेरे पे, कितना फ़क्र देख",
      },
    },
    {
      id: "node-exp-pride-context",
      conversationId: "conv-sad-gaana-1",
      type: "exploration",
      promptQuestion: "What does pride mean in this context?",
      actionType: "why",
      content:
        "### The Burden of Maternal Pride\n\nUnlike arrogant vanity, **pride** here signifies *validation*.\n\nThe artist contrasts this pure validation against his own internal burnout (*\"थक चुका हूँ मैं\"*). The pride of the mother is the emotional anchor keeping him grounded when commercial success seems elusive.",
      parentId: "node-exp-fakr",
      isMainPath: false,
      position: { x: 1050, y: 220 },
      collapsed: false,
      createdAt: Date.now() - 3000000,
      anchor: {
        sourceNodeId: "node-exp-fakr",
        text: "pride",
        start: 40,
        end: 45,
        actionType: "why",
      },
      metadata: {
        contextSentence: "Pride, honor, profound sense of dignity",
      },
    },
    {
      id: "node-exp-kahavat",
      conversationId: "conv-sad-gaana-1",
      type: "exploration",
      promptQuestion: "What does कहावत mean and how is it used here?",
      actionType: "explain",
      content:
        "### कहावत (Kahavat)\n\n**Literal Meaning:** Proverb, adage, or traditional maxim (literally *'that which is said'*).\n\n**Humorous Subversion in the Track:**\nUsually, a *कहावत* is an ancient wise saying (like *'slow and steady wins the race'*). Here, the rapper refers to the aggressive Delhi street slang phrase (*'गाँड फाड़ दूँगा'*) as if it were a timeless **figurative language** proverb! This intentional dissonance creates comedic relief amidst heavy melancholy.",
      parentId: "node-ai-1",
      isMainPath: false,
      position: { x: 550, y: 550 },
      collapsed: false,
      createdAt: Date.now() - 2800000,
      anchor: {
        sourceNodeId: "node-ai-1",
        text: "कहावत",
        start: 468,
        end: 473,
        actionType: "explain",
      },
      metadata: {
        contextSentence: "गाँड फाड़ दूँगा, एक छोटी सी कहावत सी",
      },
    },
    {
      id: "node-exp-figurative",
      conversationId: "conv-sad-gaana-1",
      type: "exploration",
      promptQuestion: "Why use figurative language here?",
      actionType: "why",
      content:
        "### Juxtaposition of Street Vulgarity & Poetic Form\n\nBy framing hyper-aggressive DHH (Desi Hip Hop) slang under the guise of **figurative language**, the writer:\n1. Defuses aggressive bravado with self-aware irony.\n2. Signals that even in his darkest sadness, the competitive spirit is still kicking.",
      parentId: "node-exp-kahavat",
      isMainPath: false,
      position: { x: 1050, y: 550 },
      collapsed: false,
      createdAt: Date.now() - 2600000,
      anchor: {
        sourceNodeId: "node-exp-kahavat",
        text: "figurative language",
        start: 260,
        end: 279,
        actionType: "why",
      },
      metadata: {
        contextSentence: "an ancient wise saying as timeless figurative language",
      },
    },
    {
      id: "node-user-2",
      conversationId: "conv-sad-gaana-1",
      type: "user",
      content: "How does the production and beat switch mirror these lyrics?",
      parentId: "node-ai-1",
      isMainPath: true,
      mainPathIndex: 2,
      position: { x: 50, y: 850 },
      collapsed: false,
      createdAt: Date.now() - 2000000,
    },
    {
      id: "node-ai-2",
      conversationId: "conv-sad-gaana-1",
      type: "assistant",
      content:
        "The track uses a **lo-fi Rhodes piano loop** paired with dry 808s.\n\nWhen he speaks of maternal love, the percussion strips away to solo keys, creating an intimate bedroom vibe. When transitioning to verses with gritty resolve, crisp hi-hat rolls enter to drive rhythmic urgency.\n\nNotice how musical dynamics echo the psychological duality we explored earlier.",
      parentId: "node-user-2",
      isMainPath: true,
      mainPathIndex: 3,
      position: { x: 50, y: 1150 },
      collapsed: false,
      createdAt: Date.now() - 1800000,
      metadata: {
        contextSentence: "Musical texture analysis and production breakdown",
      },
    },
  ],
  anchors: [
    {
      id: "anchor-1",
      sourceNodeId: "node-ai-1",
      targetNodeId: "node-exp-fakr",
      text: "फ़क्र",
      start: 228,
      end: 232,
      actionType: "explain",
      createdAt: Date.now() - 3200000,
    },
    {
      id: "anchor-2",
      sourceNodeId: "node-exp-fakr",
      targetNodeId: "node-exp-pride-context",
      text: "pride",
      start: 40,
      end: 45,
      actionType: "why",
      createdAt: Date.now() - 3000000,
    },
    {
      id: "anchor-3",
      sourceNodeId: "node-ai-1",
      targetNodeId: "node-exp-kahavat",
      text: "कहावत",
      start: 468,
      end: 473,
      actionType: "explain",
      createdAt: Date.now() - 2800000,
    },
    {
      id: "anchor-4",
      sourceNodeId: "node-exp-kahavat",
      targetNodeId: "node-exp-figurative",
      text: "figurative language",
      start: 260,
      end: 279,
      actionType: "why",
      createdAt: Date.now() - 2600000,
    },
  ],
};

export const DEMO_CONVERSATION_RECURSION: {
  conversation: Conversation;
  nodes: GraphNode[];
  anchors: TextAnchor[];
} = {
  conversation: {
    id: "conv-recursion-1",
    title: "Understanding Recursion & Call Stacks",
    rootNodeId: "node-rec-u1",
    currentNodeId: "node-rec-ai1",
    createdAt: Date.now() - 1800000,
    updatedAt: Date.now(),
  },
  nodes: [
    {
      id: "node-rec-u1",
      conversationId: "conv-recursion-1",
      type: "user",
      content: "Can you explain recursion to me simply with an intuitive mental model?",
      parentId: null,
      isMainPath: true,
      mainPathIndex: 0,
      position: { x: 50, y: 50 },
      collapsed: false,
      createdAt: Date.now() - 1700000,
    },
    {
      id: "node-rec-ai1",
      conversationId: "conv-recursion-1",
      type: "assistant",
      content:
        "**Recursion** is a programming technique where a **function calls itself** to break a complex problem into smaller identical sub-problems.\n\n### The Golden Rule\nEvery recursive function needs two pieces:\n1. **Base Case:** The condition that tells the recursion when to stop (preventing an infinite loop).\n2. **Recursive Step:** Where the function calls itself with a slightly smaller input, moving toward the base case.\n\nThink of Russian Matryoshka dolls: each doll contains a smaller doll until you reach the smallest solid doll that cannot be opened.",
      parentId: "node-rec-u1",
      isMainPath: true,
      mainPathIndex: 1,
      position: { x: 50, y: 350 },
      collapsed: false,
      createdAt: Date.now() - 1600000,
    },
    {
      id: "node-rec-exp1",
      conversationId: "conv-recursion-1",
      type: "exploration",
      promptQuestion: "How does the call stack manage when a function calls itself?",
      actionType: "explain",
      content:
        "### The Call Stack in Action\n\nWhen a function calls itself:\n1. Each call pushes a **stack frame** onto the system memory call stack.\n2. The earlier function pauses and waits for the inner call to return.\n3. Once the **base case** returns a value, the stack *unwinds*, returning values bottom-up.",
      parentId: "node-rec-ai1",
      isMainPath: false,
      position: { x: 550, y: 350 },
      collapsed: false,
      createdAt: Date.now() - 1400000,
      anchor: {
        sourceNodeId: "node-rec-ai1",
        text: "function calls itself",
        start: 56,
        end: 77,
        actionType: "explain",
      },
    },
    {
      id: "node-rec-exp2",
      conversationId: "conv-recursion-1",
      type: "exploration",
      promptQuestion: "What causes a Stack Overflow?",
      actionType: "why",
      content:
        "### Stack Overflow\n\nIf the **base case** is missing or unreachable, the recursion never terminates. Stack frames keep piling up until allocated call stack memory exceeds system limits, throwing `RangeError: Maximum call stack size exceeded`.",
      parentId: "node-rec-exp1",
      isMainPath: false,
      position: { x: 1050, y: 350 },
      collapsed: false,
      createdAt: Date.now() - 1200000,
      anchor: {
        sourceNodeId: "node-rec-exp1",
        text: "stack frame",
        start: 58,
        end: 69,
        actionType: "why",
      },
    },
  ],
  anchors: [
    {
      id: "anchor-rec-1",
      sourceNodeId: "node-rec-ai1",
      targetNodeId: "node-rec-exp1",
      text: "function calls itself",
      start: 56,
      end: 77,
      actionType: "explain",
      createdAt: Date.now() - 1400000,
    },
    {
      id: "anchor-rec-2",
      sourceNodeId: "node-rec-exp1",
      targetNodeId: "node-rec-exp2",
      text: "stack frame",
      start: 58,
      end: 69,
      actionType: "why",
      createdAt: Date.now() - 1200000,
    },
  ],
};
